apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtubez
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtubez
  template:
    metadata:
      labels:
        app: youtubez
    spec:
      containers:
        - name: youtubez
          image: limkel/youtubez:2.0
          ports:
            - containerPort: 3000  # Your Node.js application should listen on port 3000

---

apiVersion: v1
kind: Service
metadata:
  name: youtubezsvc
spec:
  selector:
    app: youtubez
  ports:
    - protocol: TCP
      port: 80  # You can use port 80 here for HTTP traffic
      targetPort: 3000  # This should match the port your Node.js application is running on (3000)
  type: NodePort
