name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # You can specify the Node.js version you need

      - name: Check Node.js version
        run: node -v

      - name: Analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-url: ${{ secrets.SONAR_HOST_URL }}
