name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # You can specify the Node.js version you need

      - name: Check Node.js version
        run: node -v

      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-url: ${{ secrets.SONAR_HOST_URL }}

      - name: Build and analyze
        run: |
          # Add your build and analysis commands here
          # For example, you can run npm install and analyze your Node.js project.
          # npm install
          # sonar-scanner
